# Generated by Django 2.2.5 on 2019-12-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=255)),
                ('series_code', models.CharField(max_length=255)),
                ('country_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('year', models.DateField()),
                ('data', models.FloatField()),
            ],
        ),
    ]
